resources:
  pipelines:
    gismo_lakeflow_pipeline:
      name: ${var.pipeline_name}
      catalog: ${var.catalog}
      schema: ${var.schema}
      serverless: true
      continuous: false
      channel: CURRENT
      edition: ADVANCED
      development: true
      libraries:
        - file:
            path: ../packages/pipeline/src/pipeline/lakeflow_pipeline.py
      environment:
        dependencies:
          # We include every dependency defined by pyproject.toml by defining an editable environment
          # that points to the folder where pyproject.toml is deployed.
          - ${workspace.root_path}/artifacts/.internal/*.whl
      configuration:
        gismo.catalog: ${var.catalog}
        gismo.schema: ${var.schema}
